version: "3.8"
services:
  changedetection:
    image: "linuxserver/changedetection.io:${TAG}"
    container_name: "changedetection"
    labels:
      - "com.centurylinklabs.watchtower.enable=${AUTO_UPDATE}"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    volumes:
      - "${CONFIG_PATH}:/config"
    ports:
      - "${PORT}:5000"
    restart: "unless-stopped"
