version: "3.8"
services:
  pihole-unbound:
    container_name: "pihole-unbound"
    image: "rlabinc/pihole-unbound:2024.02.2"
    environment:
      - "TZ=${TZ}"
      - "WEBPASSWORD=${WEBPASSWORD}"
    volumes:
      - "${ETC_PIHOLE_PATH}:/etc/pihole"
      - "${ETC_DNSMASQ_PATH}:/etc/dnsmasq.d"
#      - "${UNBOUND_PATH}:/opt/unbound/etc/unbound" #For custom Unbound conf 
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${PORT}:80/tcp"
    restart: "unless-stopped"
