version: "3.8"  
services:
  authelia:
    image: "authelia/authelia:latest@sha256:82831059ce5c1151d4ccd37f803cdf35fccbd488c80fe7f9f8de6b76adf40447"
    container_name: "authelia"
    environment:
      - "TZ=${TZ}"
    volumes:
      - "${CONFIG_PATH}:/config"
    ports:
      - "${PORT}:9091"
    restart: "unless-stopped"
