version: "3.8"
services:
  forgejo_server:
    image: "codeberg.org/forgejo/forgejo:${SERVER_TAG}"
    container_name: "forgejo_server"
    labels:
      - "com.centurylinklabs.watchtower.enable=${AUTO_UPDATE}"
      - "com.centurylinklabs.watchtower.depends-on=forgejo_db"
    depends_on:
      - "forgejo_db"
    environment:
      - "USER_UID=${PUID}"
      - "USER_GID=${PGID}"
      - "GITEA__database__DB_TYPE=mysql"
      - "GITEA__database__HOST=forgejo_db"
      - "GITEA__database__NAME=${MYSQL_DATABASE}"
      - "GITEA__database__USER=${MYSQL_USER}"
      - "GITEA__database__PASSWD=${MYSQL_PASSWORD}"
    volumes:
      - "${SERVER_PATH}:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "${SERVER_PORT}:3000"
    restart: "unless-stopped"

  forgejo_db:
    image: "linuxserver/mariadb:${DB_TAG}"
    container_name: "forgejo_db"
    labels:
      - "com.centurylinklabs.watchtower.enable=${AUTO_UPDATE}"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    volumes:
      - "${DB_PATH}:/config"
    ports:
      - "${DB_PORT}:3306"
    restart: "unless-stopped"
