version: "3.8"
services:
  nextcloud_app:
    image: "nextcloud:28.0.4"
    container_name: "nextcloud_app"
    depends_on:
      - "nextcloud_db"
      - "nextcloud_redis"
    environment:
      - "POSTGRES_HOST=nextcloud_db:5432"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "REDIS_HOST=nextcloud_redis"
      - "REDIS_HOST_PORT=6379"
      - "REDIS_HOST_PASSWORD=${REDIS_PASSWORD}"
      - "PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}"
      - "PHP_UPLOAD_LIMIT=${PHP_UPLOAD_LIMIT}"
      - "APACHE_DISABLE_REWRITE_IP=${APACHE_DISABLE_REWRITE_IP}"
    volumes:
      - "${CONFIG_PATH}:/var/www/html"
      - "${DATA_PATH}:/var/www/html/data"
    ports:
      - "${APP_PORT}:80"
    restart: "unless-stopped"

  nextcloud_cron:
    image: "nextcloud:28.0.4"
    container_name: "nextcloud_cron"
    depends_on:
      - "nextcloud_app"
    entrypoint: /cron.sh
    volumes:
      - "${CONFIG_PATH}:/var/www/html"
      - "${DATA_PATH}:/var/www/html/data"
    restart: "unless-stopped"

  nextcloud_db:
    image: "postgres:16.2"
    container_name: "nextcloud_db"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - "${DB_PATH}:/config"
    ports:
      - "${DB_PORT}:5432"
    restart: "unless-stopped"
    
  nextcloud_redis:
    image: "redis:7.2.4"
    container_name: "nextcloud_redis"
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    volumes:
      - "${REDIS_PATH}:/data"
    ports:
      - "${REDIS_PORT}:6379"
    restart: "unless-stopped"
