version: "3.8"
services:
  glances:
    image: "nicolargo/glances:latest"
    container_name: "glances"
    hostname: "Onix"
    pid: "host"
    environment:
      - "GLANCES_OPT=-w"
    ports:
      - "61208:61208"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/:/mnt/root"
    restart: "unless-stopped"
