version: "3.8"
services:
  glances:
    image: "nicolargo/glances:${TAG}"
    container_name: "glances"
    pid: "host"
    labels:
      - "com.centurylinklabs.watchtower.enable=${AUTO_UPDATE}"
    environment:
      - "GLANCES_OPT=-w"
    ports:
      - "61208:61208"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: "unless-stopped"
