version: "3.8"
services:
  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    labels:
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    restart: unless-stopped
