version: "3.8"
services:
  adguardhome:
  adguardhome-sync:
    image: "linuxserver/adguardhome-sync:0.6.6"
    container_name: "adguardhome-sync"
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    volumes:
      - "${SYNC_PATH}:/config"
    ports:
      - "${SYNC_PORT}:8080"
    restart: "unless-stopped"
