version: "3.8"
services:
  uptime-kuma:
    image: "louislam/uptime-kuma:${TAG}"
    container_name: "uptime-kuma"
    labels:
      - "com.centurylinklabs.watchtower.enable=${AUTO_UPDATE}"
    volumes:
      - "${CONFIG_PATH}:/app/data"
    ports:
      - "${PORT}:3001"
    restart: "unless-stopped"
